services:
  testdb:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coupon_management_api_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rspec
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      testdb:
        condition: service_healthy
    environment:
      RAILS_ENV: test
      DATABASE_HOST: testdb
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_MAX_THREADS: 5
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
